services:
  - type: web
    name: docscreen-backend
    runtime: docker
    dockerfilePath: backend/Dockerfile
    dockerContext: backend
    plan: free
    envVars:
      - key: PORT
        value: 8000

  - type: web
    name: docscreen-frontend
    runtime: node
    rootDir: frontend
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NEXT_PUBLIC_API_URL
        fromService:
          type: web
          name: docscreen-backend
          property: host
